FROM dongduong/ubuntu-jdk-mysql:slim
VOLUME /tmp
ADD spring-security-oauth2-server.war app.war
RUN sh -c 'touch /app.war'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.war" ]